name: Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
permissions:
  contents: read
jobs:
  publish:
    permissions:
      actions: write
    runs:
      using: 'docker'
      image: 'Dockerfile'
    steps:
      - name: "Checkout"
      - name: "Publish new version to TER"
        with:
          api-token: ${{ secrets.TYPO3_API_TOKEN }}